#!/usr/bin/env ruby
#
# Simple implementation of regression tests for xml generated by parse-speeches.rb
# N.B. Need to pre-populate reference xml files with those that have previously been generated.
# In other words, this is only useful for checking that any refactoring has not caused a regression in behaviour.
#
# Requirement: xmldiff - http://www.logilab.org/projects/xmldiff/

$:.unshift "#{File.dirname(__FILE__)}/lib"

require 'people'
require 'hansard_parser'
require 'configuration'
require 'optparse'

from_date = Date.new(2006, 1, 1)
to_date = Date.new(2008, 6, 1)

conf = Configuration.new

# First load people back in so that we can look up member id's
people = People.read_members_csv("#{File.dirname(__FILE__)}/data/members.csv")

parser = HansardParser.new(people)

date = from_date
while date <= to_date
  xml_filename = "debates#{date}.xml"
  new_xml_path = "#{conf.xml_path}/scrapedxml/debates/#{xml_filename}"
  ref_xml_path = "ref/#{xml_filename}"
  parser.parse_date(date, new_xml_path)
  
  if File.exists?(new_xml_path)
    # Now compare generated and reference xml
    system("xmldiff #{new_xml_path} #{ref_xml_path}")
    if $? != 0
      puts "Regression tests FAILED on date #{date}!"
      exit
    end
  end
  date = date + 1
end

puts "Regression tests all passed!"
