#!/usr/bin/env ruby
# frozen_string_literal: true

require "bundler/setup"
Bundler.require(:default, ENV.fetch("RAILS_ENV", "development").to_sym)

$LOAD_PATH.unshift File.expand_path("../lib", __dir__).to_s

require_relative "../lib/configuration"

Dir[File.expand_path("../lib/**/*.rb", __dir__)].sort.each do |f|
  puts "requiring #{f}..."
  require_relative f
end

require "irb"
IRB.start
