#!/usr/bin/env ruby
# frozen_string_literal: true

require "bundler/setup"

$LOAD_PATH.unshift File.expand_path("../lib", __dir__).to_s

%w[configuration count ]
require_relative "../lib/configuration"

Dir[File.expand_path("../lib/**/*.rb", __dir__)].sort.each do |f|
  puts "requiring #{f}..."
  require_relative f
end

require "irb"
IRB.start
