name: Update parent repo
on:
  push:
    branches:
      - main

jobs:
  update_parent:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          event-type: openaustralia-parser-updated
          repository: openaustralia/openaustralia
          token: ${{ secrets.OPENAUSTRALIA_ACCESS_TOKEN }}
