name: Ruby checks
on:
  push:
    branches: [main]
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - run: sudo apt-get update && sudo apt-get install -y libmagickwand-dev # needed to build the rmagick native extension
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - run: cp configuration.yml.example configuration.yml
    - run: bundle exec rspec
  scripts:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - run: sudo apt-get update && sudo apt-get install -y libmagickwand-dev # needed to build the rmagick native extension
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - run: cp configuration.yml.example configuration.yml
    - run: bundle exec ./parse-members.rb --no-load
    - run: bundle exec ./postcodes.rb --no-load
    - run: bundle exec rubocop
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - run: sudo apt-get update && sudo apt-get install -y libmagickwand-dev # needed to build the rmagick native extension
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - run: bundle exec rubocop
